language: python
python:
  - "3.6"
jobs:
  include:
    - name: 'Pylint'
      install:
        - pip install -r requirements.txt
        - pip install './code[gpu]'
        - pip install pylint pylint-quotes
      before_script:
        - cd code
      script:
        - pylint groove2groove
    - name: 'Code style'
      install:
        - pip install pycodestyle pydocstyle isort
      before_script:
        - cd code
      script:
        - pycodestyle groove2groove
        - pydocstyle groove2groove
        - isort --check-only --recursive --diff groove2groove
